services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    command: ["flask", "--app", "bluesea_app:create_app", "run", "--debug", "--host", "0.0.0.0", "--port", "5000"]
    environment:
      FLASK_APP: bluesea_app:create_app
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      CORS_ORIGINS: http://localhost:5173
      UPLOAD_FOLDER: /app/uploads
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    environment:
      VITE_API_BASE_URL: http://localhost:5000
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  frontend_node_modules:
